### ISSUE TITLE
Финансирование

### ISSUE THREAD

**Issue by creakosta** [maximnara/cordova-plugin-yandex-ads#1]
Здравствуйте!
Я хотел бы перейти на медиацию от Яндекса и нашел ваш плагин. Я мог бы профинансировать доработку плагина - поддержку баннера и получения согласия GDPR под ios и андроид. Если это возможно, то напишите мне на почту creakosta@mail.ru или в телеграм @creakosta

**Comment by maximnara** [comment]
Спасибо большое за помощь в развитии. В новом релизе мы добавили работу с баннерной рекламой.

**Comment by maximnara** [comment]
В @1.1.0 добавили поддержку GDPR.
