### ISSUE TITLE
Неправильный размер банера

### ISSUE THREAD

**Issue by anunakenki** [maximnara/cordova-plugin-yandex-ads#2]
Проблема с размером баннера (не помещается в выделенный блок.

![ баннер обрезается снизу ](https://user-images.githubusercontent.com/9458977/169863070-476986a5-a153-42ed-9c12-f758437539de.jpg)

**Comment by maximnara** [comment]
Зависит от того какой размер баннера вы указали при инициализации.

```
await YandexAds.init({ 
  rewardedBlockId: 'YOUR_REWARDER_BLOCK_ID',
  interstitialBlockId: 'YOUR_INTERSTITIAL_ID',
  bannerBlockId: 'YOOUR_BANNER_ID',
  options: { // This is for banner ads
    overlap: false, // Show under all elements (works only on android)
    bannerAtTop: true, // Show banner on top of screen, otherwise on bottom
    bannerSize: YandexAds.BANNER_240x400, // Your banner size
  },
});

```

Здесь параметр bannerSize, список размеров можно найти в README

**Comment by anunakenki** [comment]
При инициализации размер банера: BANNER_320x50 и контейнер для баннера создаётся правильного размера (предположительно), но сам баннер в блок не помещается (имеет большую высоту). Такое поведение наблюдается со всеми размерами.

**Comment by maximnara** [comment]
Возможно это стандартное поведение библиотеки yandex, когда нет баннера подходящего размера вставляется то что есть.

**Comment by anunakenki** [comment]
Подобное поведение наблюдается и с тестовым баннером 320×50. Складывается впечатление, что вёрстка баннера "едет" по каким либо причинам. Есть ли факторы, которые могут влиять на это?

**Comment by maximnara** [comment]
Напишите в личку плиз telegram: `@luzhkov`
Попробуем разобраться
