### ISSUE TITLE
Обновление версии SDK до 6 и добавление рекламы при открытии приложения

### ISSUE THREAD

**Issue by applecat** [maximnara/cordova-plugin-yandex-ads#8]
Возможно ли обновление версии SDK до свежей 6?

И добавление нового формата рекламы при открытии приложения? Довольно интересный формат, для Cordova приложений думаю особо актуальный из-за того, что встроить баннер непосредственно в верстку нет возможности.

З.Ы. Спасибо за уникальный плагин! Аналогов мне найти не удалось. Под Capacitor тоже работает.
З.З.Ы. Напишите, куда можно скинуть донат на развитие =)

**Comment by maximnara** [comment]
Привет! Спасибо за интерес к плагину. 
Скинуть донат можно сюда https://boosty.to/maximnara
В ближайшее время думаю обновлю SDK.

**Comment by maximnara** [comment]
Сделал обновление до 6 версии + app open ads. Можете попробовать поставить версию плагина 2.0.1
